### Replace placeholders
# token = JWT
@token = placeholder
# fingerprint = Device Fingerprint
@fingerprint = Browser

### Base URL
@host = https://localhost:7000

### Register
# I
POST {{host}}/api/auth/register
Content-Type: application/json
Fingerprint: {{fingerprint}}

{
    "handle": "eris",
    "name": "Eris",
    "uniqueName": "eris",
    "email": "eris@konosuba.gg",
    "password": "?Ok4",
    "role": "Admin"
}

### Login
# I
POST {{host}}/api/auth/login
Content-Type: application/json
Fingerprint: {{fingerprint}}

{
    "uniqueName": "eris",
    "password": "?Ok4"
}

### Logout
# Invalidate Refresh Token by deleting it on the database.
# Logout User on all devices.
POST {{host}}/api/auth/logout
Authorization: Bearer {{token}}
Fingerprint: {{fingerprint}}
