### Base URL
@host = https://localhost:7000

### Logout
# Invalidate Refresh Token by deleting it on the database.
# Logout User on all devices.
POST {{host}}/api/auth/logout

### Refresh Token
# Generate Access Token if Refresh Token is not expired.
GET {{host}}/api/auth/refresh-token

### Login
# I
POST {{host}}/api/auth/login
Content-Type: application/json

{
    "uniqueName": "kazuma",
    "password": "?Ok4"
}

### Register
# I
POST {{host}}/api/auth/register
Content-Type: application/json

{
    "handle": "kazuma",
    "name": "Kazuma",
    "uniqueName": "kazuma",
    "email": "kazuma@konosuba.gg",
    "password": "?Ok4",
    "role": "Admin"
}

### Login
# II
POST {{host}}/api/auth/login
Content-Type: application/json

{
    "uniqueName": "aqua",
    "password": "?Ok4"
}

### Register
# II
POST {{host}}/api/auth/register
Content-Type: application/json

{
    "handle": "aqua",
    "name": "Aqua",
    "uniqueName": "aqua",
    "email": "aqua@konosuba.gg",
    "password": "?Ok4",
    "role": "Admin"
}

### Login
# III
POST {{host}}/api/auth/login
Content-Type: application/json

{
    "uniqueName": "megumin",
    "password": "?Ok4"
}

### Register
# III
POST {{host}}/api/auth/register
Content-Type: application/json

{
    "handle": "megumin",
    "name": "Megumin",
    "uniqueName": "megumin",
    "email": "megumin@konosuba.gg",
    "password": "?Ok4",
    "role": "Admin"
}

### Login
# IV
POST {{host}}/api/auth/login
Content-Type: application/json

{
    "uniqueName": "darkness",
    "password": "?Ok4"
}

### Register
# IV
POST {{host}}/api/auth/register
Content-Type: application/json

{
    "handle": "darkness",
    "name": "Darkness",
    "uniqueName": "darkness",
    "email": "darkness@konosuba.gg",
    "password": "?Ok4",
    "role": "Admin"
}
