### Replace placeholders
# id = GUID
@id = placeholder
# token = JWT
@token = placeholder
# fingerprint = Device Fingerprint
@fingerprint = Browser

### Base URL
@host = https://localhost:7000

### GET ALL
GET {{host}}/api/players
Authorization: Bearer {{token}}
Fingerprint: {{fingerprint}}

### GET
GET {{host}}/api/player/{{id}}
Authorization: Bearer {{token}}
Fingerprint: {{fingerprint}}

### POST
POST {{host}}/api/player
Content-Type: application/json
Authorization: Bearer {{token}}
Fingerprint: {{fingerprint}}

{
    "handle": "yunyun",
    "name": "Yunyun",
    "uniqueName": "yunyun",
    "email": "yunyun@konosuba.gg",
    "password": "?Ok4",
    "role": "Player"
}

### PUT
PUT {{host}}/api/player/{{id}}
Content-Type: application/json
Authorization: Bearer {{token}}
Fingerprint: {{fingerprint}}

{
    "handle": "wiz",
    "name": "Wiz",
    "uniqueName": "wiz",
    "email": "wiz@konosuba.gg",
    "password": "?Ok4",
    "role": "Player"
}

### DELETE
DELETE {{host}}/api/player/{{id}}
Authorization: Bearer {{token}}
Fingerprint: {{fingerprint}}
