### Replace placeholders
# id = GUID
@id = placeholder
# token = JWT
@token = placeholder
# fingerprint = Device Fingerprint
@fingerprint = Browser

### Base URL
@host = https://localhost:7000

### GET ALL
GET {{host}}/api/sessions
Authorization: Bearer {{token}}
Fingerprint: {{fingerprint}}

### GET
GET {{host}}/api/session/{{id}}
Authorization: Bearer {{token}}
Fingerprint: {{fingerprint}}

### POST
POST {{host}}/api/session
Content-Type: application/json
Authorization: Bearer {{token}}
Fingerprint: {{fingerprint}}

{
    "id": "{{token}}",
    "fingerprint": "Browser",
    "expiry": "2022-01-01T00:00:00.8696969"
}

### PUT
PUT {{host}}/api/session/{{id}}
Content-Type: application/json
Authorization: Bearer {{token}}
Fingerprint: {{fingerprint}}

{
    "id": "{{token}}",
    "fingerprint": "Android",
    "expiry": "2028-01-01T00:00:00.6969698"
}

### DELETE
DELETE {{host}}/api/session/{{id}}
Authorization: Bearer {{token}}
Fingerprint: {{fingerprint}}
