### Base URL
@host = https://localhost:7000

### Greetings
# Replace "JWT" with the received Token response when you successfully register or login using the authentication endpoints.
GET {{host}}/api/test/greetings
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI2YzllMzdkLWExYmQtNDA2Ny1hODJkLTU0NjdhY2YyYzBmNyIsInJvbGUiOiJBZG1pbiIsImp0aSI6IjEyODgzY2IyLWI2ODAtNGEwOS04MDZkLThhYzU3OTE2MmE1YSIsImV4cCI6MTY4NTEyNDU3OSwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzAwMCIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjcwMDAifQ.V33MlHoLXFu-zT91cig7W6ym6zNtbt2H29-T8M-sAX4FiUZ_ddDC7f4QHUGDctjLL0hRjjVGl6qGl1zKWzIUjA
Fingerprint: Browser

### Session
# Get User Session
GET {{host}}/api/test/session
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI2YzllMzdkLWExYmQtNDA2Ny1hODJkLTU0NjdhY2YyYzBmNyIsInJvbGUiOiJBZG1pbiIsImp0aSI6IjEyODgzY2IyLWI2ODAtNGEwOS04MDZkLThhYzU3OTE2MmE1YSIsImV4cCI6MTY4NTEyNDU3OSwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzAwMCIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjcwMDAifQ.V33MlHoLXFu-zT91cig7W6ym6zNtbt2H29-T8M-sAX4FiUZ_ddDC7f4QHUGDctjLL0hRjjVGl6qGl1zKWzIUjA
Fingerprint: Browser
