### Base URL
@host = https://localhost:7000

### Greetings
# Replace "Token" with the JWT response received when you successfully register or login using the authentication endpoints.
GET {{host}}/api/test/greetings
Authorization: Bearer Token

### User Refresh Token
GET {{host}}/api/test/user-refresh-token
Authorization: Bearer Token
