// <auto-generated />
using System;
using Game.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Game.Infrastructure.Migrations
{
    [DbContext(typeof(GameDBContext))]
    [Migration("20230525100558_initialize")]
    partial class initialize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Game.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UniqueName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6994ed90-de07-4b48-aab9-35ba7a993242"),
                            CreationStamp = new DateTime(2023, 5, 25, 10, 5, 56, 385, DateTimeKind.Utc).AddTicks(1765),
                            Email = "kazuma@konosuba.gg",
                            Handle = "kazuma",
                            Name = "Kazuma",
                            PasswordHash = "$2a$11$OuK6MmyqyBfB07LgbhUtM.92LjB/X6ZYjOigtVpCOzuX8.t6mHI6K",
                            Role = 1,
                            UniqueName = "kazuma"
                        },
                        new
                        {
                            Id = new Guid("848473bf-884d-4681-86fb-a1ca3ef7f8f7"),
                            CreationStamp = new DateTime(2023, 5, 25, 10, 5, 56, 867, DateTimeKind.Utc).AddTicks(7135),
                            Email = "aqua@konosuba.gg",
                            Handle = "aqua",
                            Name = "Aqua",
                            PasswordHash = "$2a$11$GyRI3UWjZDzthpMGIE0B4.kCfXkqDHXIGZwi8/TQcWqKsYErYksLa",
                            Role = 1,
                            UniqueName = "aqua"
                        },
                        new
                        {
                            Id = new Guid("bcb0c1f7-1431-4a35-b582-86ed9b0fbac7"),
                            CreationStamp = new DateTime(2023, 5, 25, 10, 5, 57, 386, DateTimeKind.Utc).AddTicks(376),
                            Email = "megumin@konosuba.gg",
                            Handle = "megumin",
                            Name = "Megumin",
                            PasswordHash = "$2a$11$5e34uy3KfODp38oyvYg/Auj63o/wAGFWbYZ0zDITmwkkIRASpNsAO",
                            Role = 1,
                            UniqueName = "megumin"
                        },
                        new
                        {
                            Id = new Guid("b01740c0-8ce8-4bef-ac8f-2d244084772b"),
                            CreationStamp = new DateTime(2023, 5, 25, 10, 5, 57, 891, DateTimeKind.Utc).AddTicks(8476),
                            Email = "darkness@konosuba.gg",
                            Handle = "darkness",
                            Name = "Darkness",
                            PasswordHash = "$2a$11$OyioTJLxr8fa8i5Tcgm6XOXmSUasRV3jSb1CcB/BtrW7YZ7xmrlF6",
                            Role = 1,
                            UniqueName = "darkness"
                        });
                });

            modelBuilder.Entity("Game.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Expiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JTI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
