// <auto-generated />
using System;
using Game.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Game.Infrastructure.Migrations
{
    [DbContext(typeof(GameDBContext))]
    [Migration("20230712130909_Initialize")]
    partial class Initialize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Game.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UniqueName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-fffffffffff1"),
                            CreationStamp = new DateTime(2023, 7, 12, 13, 9, 6, 835, DateTimeKind.Utc).AddTicks(7918),
                            Email = "kazuma@konosuba.gg",
                            Handle = "kazuma",
                            Name = "Kazuma",
                            PasswordHash = "$2a$11$W8ypLTkrD/s0JCNNKJQQnOEJSlUf2kKJrt9ggO.biTqEm3lWevkP.",
                            Role = 1,
                            UniqueName = "kazuma"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-fffffffffff2"),
                            CreationStamp = new DateTime(2023, 7, 12, 13, 9, 7, 407, DateTimeKind.Utc).AddTicks(6922),
                            Email = "aqua@konosuba.gg",
                            Handle = "aqua",
                            Name = "Aqua",
                            PasswordHash = "$2a$11$bvSe6PD9kiWVI7HxrwlccOh0/.bu7DYxyDvK9.0L3Rc1USgXMK3WS",
                            Role = 1,
                            UniqueName = "aqua"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-fffffffffff3"),
                            CreationStamp = new DateTime(2023, 7, 12, 13, 9, 7, 963, DateTimeKind.Utc).AddTicks(6599),
                            Email = "megumin@konosuba.gg",
                            Handle = "megumin",
                            Name = "Megumin",
                            PasswordHash = "$2a$11$nEV7DxtYOYoNCx8P02IIH.3CsqsmVBsb5cwVZUqmTRUV882uhk4se",
                            Role = 1,
                            UniqueName = "megumin"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-fffffffffff4"),
                            CreationStamp = new DateTime(2023, 7, 12, 13, 9, 8, 517, DateTimeKind.Utc).AddTicks(9744),
                            Email = "darkness@konosuba.gg",
                            Handle = "darkness",
                            Name = "Darkness",
                            PasswordHash = "$2a$11$TL5Sq0pKrxO6bWnLN4CpJ.oU9XNi./xwyt3fCdxsU18zzmRGO5.TO",
                            Role = 1,
                            UniqueName = "darkness"
                        });
                });

            modelBuilder.Entity("Game.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Expiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
