// <auto-generated />
using System;
using Game.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Game.Infrastructure.Migrations
{
    [DbContext(typeof(GameDBContext))]
    [Migration("20230602094030_Initialize")]
    partial class Initialize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Game.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UniqueName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = new Guid("93cbf201-8dd8-4306-a542-1e3e91d1b356"),
                            CreationStamp = new DateTime(2023, 6, 2, 9, 40, 27, 849, DateTimeKind.Utc).AddTicks(8290),
                            Email = "kazuma@konosuba.gg",
                            Handle = "kazuma",
                            Name = "Kazuma",
                            PasswordHash = "$2a$11$Ql/mnmJyyGu.zbU5VAE0Lemq57t89NjRKby6EZac57GOmq9ad2H0m",
                            Role = 1,
                            UniqueName = "kazuma"
                        },
                        new
                        {
                            Id = new Guid("1559905d-71f3-4c98-a69f-8fd7cf8d8a53"),
                            CreationStamp = new DateTime(2023, 6, 2, 9, 40, 28, 342, DateTimeKind.Utc).AddTicks(2156),
                            Email = "aqua@konosuba.gg",
                            Handle = "aqua",
                            Name = "Aqua",
                            PasswordHash = "$2a$11$R0HMtACMOOg.ST4K8gLAvOfHf9/MEe9CLJw3Sns4Niykiuw6gqoYG",
                            Role = 1,
                            UniqueName = "aqua"
                        },
                        new
                        {
                            Id = new Guid("a195bc36-a9fe-40f9-baaf-be5b100d4a78"),
                            CreationStamp = new DateTime(2023, 6, 2, 9, 40, 28, 835, DateTimeKind.Utc).AddTicks(9378),
                            Email = "megumin@konosuba.gg",
                            Handle = "megumin",
                            Name = "Megumin",
                            PasswordHash = "$2a$11$j54jpz3wZsKWtgm0zJjK1uUck28MPY2ny7.KYIxV8c8R//GFq9O3a",
                            Role = 1,
                            UniqueName = "megumin"
                        },
                        new
                        {
                            Id = new Guid("441c386a-4dff-47fd-827a-3310bdeb8074"),
                            CreationStamp = new DateTime(2023, 6, 2, 9, 40, 29, 475, DateTimeKind.Utc).AddTicks(3605),
                            Email = "darkness@konosuba.gg",
                            Handle = "darkness",
                            Name = "Darkness",
                            PasswordHash = "$2a$11$KLWojnpLB4fS.woDN8/Cb.6IoVQJrdShkvwZz81dg3lxen7WGbsBO",
                            Role = 1,
                            UniqueName = "darkness"
                        });
                });

            modelBuilder.Entity("Game.Domain.Entities.Session", b =>
                {
                    b.Property<string>("JTI")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Expiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JTI");

                    b.ToTable("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
