// <auto-generated />
using System;
using Game.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Game.Infrastructure.Migrations
{
    [DbContext(typeof(GameDBContext))]
    partial class GameDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Game.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UniqueName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2b92e20-bc64-431b-98d1-c5b41c9d7396"),
                            CreationStamp = new DateTime(2023, 5, 26, 16, 8, 58, 334, DateTimeKind.Utc).AddTicks(4153),
                            Email = "kazuma@konosuba.gg",
                            Handle = "kazuma",
                            Name = "Kazuma",
                            PasswordHash = "$2a$11$dcPkpp7cHUMXof5wkx5o4OdK/wpGoRYHNBRvFK3x6Her1bKGq9n0a",
                            Role = 1,
                            UniqueName = "kazuma"
                        },
                        new
                        {
                            Id = new Guid("a08c82e1-9fe3-478f-8ace-c88fed14ee71"),
                            CreationStamp = new DateTime(2023, 5, 26, 16, 8, 58, 819, DateTimeKind.Utc).AddTicks(5142),
                            Email = "aqua@konosuba.gg",
                            Handle = "aqua",
                            Name = "Aqua",
                            PasswordHash = "$2a$11$Ic1lVC.SwCxoO1c.4LdyOOTw5/g025W8M2pdqXEF.Y3BMGjMxIULW",
                            Role = 1,
                            UniqueName = "aqua"
                        },
                        new
                        {
                            Id = new Guid("2d7a604f-5b2e-49b1-a5af-2a05772ad823"),
                            CreationStamp = new DateTime(2023, 5, 26, 16, 8, 59, 299, DateTimeKind.Utc).AddTicks(3729),
                            Email = "megumin@konosuba.gg",
                            Handle = "megumin",
                            Name = "Megumin",
                            PasswordHash = "$2a$11$7n57nZGS3CeL6U7aTKHE0e7vcX0BG4WxpHFNDk0PWS9DxIxrm/BPS",
                            Role = 1,
                            UniqueName = "megumin"
                        },
                        new
                        {
                            Id = new Guid("2f19c652-8a18-4980-950f-0222d1dbe301"),
                            CreationStamp = new DateTime(2023, 5, 26, 16, 8, 59, 790, DateTimeKind.Utc).AddTicks(4016),
                            Email = "darkness@konosuba.gg",
                            Handle = "darkness",
                            Name = "Darkness",
                            PasswordHash = "$2a$11$uMX8rpWZJ/.YryYt8MY..e3FiPHgn120GhtHEReCxEA0brkybhmlK",
                            Role = 1,
                            UniqueName = "darkness"
                        });
                });

            modelBuilder.Entity("Game.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Expiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JTI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
